version: '3.8'

services:
  dashboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: presidio-devops-dashboard
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
